# this file is for configuring multiple container

version: '3.8'

services:
  postgres:
    image: "postgres" # from hub.docker.com
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_DB: users
      POSTGRES_PASSWORD: secretpassword

  redis:
    image: redis
    ports:
      - 6379:6379